```yaml
name: Node.js CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # PostgreSQL database service container
      postgres:
        image: postgres:14 # Using a specific stable version of PostgreSQL
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432 # Map container port 5432 to host port 5432
        options: >-
          --health-cmd pg_isready -d test_db -U test_user
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5 # Wait for PostgreSQL to be healthy

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: Cache npm dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm # Cache the global npm cache directory
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci # Installs dependencies from package-lock.json

    - name: Wait for PostgreSQL to be ready
      # Using netcat (nc) to check if the PostgreSQL port is open and listening
      # This ensures the database is fully ready before the application tries to connect
      run: |
        echo "Waiting for PostgreSQL to become available..."
        for i in $(seq 1 30); do
          nc -z localhost 5432 >/dev/null 2>&1
          if [ $? -eq 0 ]; then
            echo "PostgreSQL is ready on port 5432!"
            break
          fi
          echo "Still waiting for PostgreSQL... ($i/30)"
          sleep 1
        done
        # Fail the workflow if PostgreSQL is not ready after 30 seconds
        nc -z localhost 5432 >/dev/null 2>&1 || { echo "PostgreSQL did not become ready after 30 seconds."; exit 1; }

    - name: Run tests
      env:
        # These environment variables must match what your Node.js application expects
        # for connecting to PostgreSQL, especially in a test environment.
        DB_HOST: localhost
        DB_PORT: 5432
        DB_NAME: test_db
        DB_USER: test_user
        DB_PASSWORD: test_password
        # Add any other environment variables your tests might need (e.g., specific API keys)
      run: npm test
```